# This makefile exists ONLY to provide the clean rule for the TI builds

# Recipe to clean all compiled objects
.phony clean:
	-rm *.o || true
	-rm *.i || true
	-rm *.s || true
	-rm *.lst || true
	-rm *.elf || true
	-rm *.map || true
	-rm *.bin || true

